# Generated by Django 4.0.4 on 2022-06-02 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_alter_tutorial_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGameRecord',
            fields=[
                ('NAME', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('COUNT', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.DateTimeField(auto_now_add=True)),
                ('SCORE', models.IntegerField(default=0)),
                ('MODE', models.CharField(default='easy', max_length=10)),
                ('NAME', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
